// src/Products.ts
export const products = [
  {
    id: "1",
    title: "Elegant Abaya",
    price: 50,
    description: "Modern and modest",
    image: "/img15.webp",
    images: ["/img17.webp", "/img14.webp" , "/img13.webp" , "/img13.webp"],
  },
  {
    id: "2",
    title: "Stylish Dress",
    price: 75,
    description: "Elegant occasion dress",
    image: "/img2.webp",
    images: ["/img1.webp", "/img3.webp" , "/img4.webp", "/img5.webp", "/img6.webp", "/img7.webp", "/img8.webp", "/img9.webp", "/img10.webp", "/img11.webp"],
  },
  {
    id: "3",
    title: "Casual Hijab",
    price: 20,
    description: "Everyday comfort",
    image: "/img25.webp",
    images: [ "/img23.webp", "/img24.webp","/img27.webp", "/img28.webp", "/img26.webp"],
  },
  {
    id: "4",
    title: "Modest Set",
    price: 60,
    description: "Two piece outfit",
    image: "/img22.webp",
    images: ["/img18.webp", "/img19.webp", "/img20.webp", "/img21.webp", "/img18.webp"],
  },
  {
    id: "5",
    title: "Chic Kimono",
    price: 45,
    description: "Soft silky kimono",
    image: "/img29.webp",
    images: [ "/img29.webp","/img30.webp", "/img31.webp", "/img32.webp"],
  },
  {
    id: "6",
    title: "Prayer Outfit",
    price: 35,
    description: "Comfortable praying suit",
    image: "/img33.webp",
    images: ["/img33.webp", "/img35.webp", "/img36.webp", "/img37.webp", "/img38.webp", "/img34.webp"],
  },
  {
    id: "7",
    title: "Printed Scarf",
    price: 18,
    description: "Elegant printed scarf",
    image: "/img39.webp",
    images: ["/img39.webp", "/img40.webp", "/img41.webp", "/img42.webp", "/img43.webp", "/img44.webp"],
  },
];
